### PR TITLE
fix #25

### LINKED ISSUE #25: some user report conda command not found in provenance function
see:
https://github.com/CDAT/jupyter-vcdat/issues/44

### PR DESCRIPTION
**Pull request by doutriaux1**
if conda is not in path but rather a bash function this works

### CODE REVIEW

**Comment by doutriaux1** [comment]
@William-Hill this should fix your issue

**Comment by doutriaux1** [comment]
@durack1 adresses your version issue https://github.com/CDAT/cdat/issues/2229

**Comment by durack1** [comment]
@doutriaux1 may as well auto-close this issue then

Fix CDAT/cdat#2229

**Comment by durack1** [comment]
@doutriaux1 I also wonder whether this will trigger a new conda build - will this propagate into a new env if I generate it post-PR-merge?

**Comment by doutriaux1** [comment]
@durack1 in nighlty yes, but i also plan to push the 8.1 tag back to this and update conda-forge

**Comment by durack1** [comment]
@doutriaux1 sounds good, either that or a 8.1.1 to ensure that things don't get tangled

**Review by William-Hill — APPROVED** [review]

**Pull request merged**
