### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Review by dnadeau4 — APPROVED** [review]

**Comment by dnadeau4** [comment]
@doutriaux1 I will try genutil with your change when I get a chance.  run_test.py had some `string` issue in python3 with cdat_info.

**Comment by doutriaux1** [comment]
the askAnonymous which uses raw_input gave me trouble, it should be good now though.

**Comment by dnadeau4** [comment]
Are you taking care of `cdat-info-feedstock`?   You need to create a tarball in the `resources` directory.

**Comment by doutriaux1** [comment]
will do, but it's part of cdat itself so I will only update the nightlies for now
feedtock will be for `2.12`

**Comment by doutriaux1** [comment]
let me know when it works for you. I'll merge in master

**Comment by dnadeau4** [comment]
OK.

**Comment by dnadeau4** [comment]
@doutriaux1 can you check if .encond('utf-8') works on Python 2.7 as well.  You might need a __future__ thing.

**Comment by doutriaux1** [comment]
@dnadeau4 good point

**Comment by doutriaux1** [comment]
yep it works. Just checked.

**Pull request merged**
