### PR TITLE
Provenance tools

### PR DESCRIPTION
**Pull request by doutriaux1**
@durack1 @danlipsa @dnadeau4 @zshaheen first draft

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 is there a single identifier for the "whole" thing? The component pieces are great, but for a single provenance string it's a bit overkill

**Comment by doutriaux1** [comment]
hum... Please a template/list of things of the string you'd like I'll come up with a function to generate something.

**Comment by zshaheen** [comment]
@doutriaux1 Looks good to me. 

When you install a package from source and run `conda list`, it only gives the version that's in `setup.py`, which often isn't that descriptive. In contrast, installing via Anaconda gives the exact version, so a person can get the exact package. I don't think there's a way to get the git hash from the installation (running a subprocess with `git rev-parse HEAD` needs to be in the source dir). Not really important I guess.

**Comment by doutriaux1** [comment]
@zshaheen our nightlies do contain the git hash in the version number so we're good like that.

**Comment by doutriaux1** [comment]
@zshaheen for installation from source, I'm planning to edit the setup.py of our packages to reflect the git hash as well.

**Comment by zshaheen** [comment]
@doutriaux1 Cool, sounds good.

**Comment by durack1** [comment]
@doutriaux1 @zshaheen ideally, I'd like a single string that I can embed into the global attributes of generated files, so succinct is the key. A previous version of this string was: `:host = "ocean.llnl.gov; UVCDAT version: 2.4.0rc1-8-gd23939e; Python version: 2.7.10 (default, Sep 30 2015, 10:29:36); [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]"`

This worked with the earlier `cdat_version()` reporting, but as things have now changed (and conda is being used routinely) this needs to be reconfigured.

**Pull request merged**
